# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Tyas
email: matt@matthewtyas.com
description: > # this means to ignore newlines until "baseurl:"
  Matt Tyas - Lead interaction designer at Co-op digital and product owner of the Co-op design manual. Also a co-founder of Manchester's Finest.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matt-tyas.github.io/" # the base hostname & protocol for your site
twitter_username: matttyas
github_username:  matt-tyas

# Build settings
markdown: kramdown
